#!/bin/bash

set -euo pipefail

# ================================
# Variables

PUSH=false

IMAGE_DEP_PCRE_VERSION="${IMAGE_DEP_PCRE_VERSION:-}"
IMAGE_DEP_PCRE_COMMIT="${IMAGE_DEP_PCRE_COMMIT:-}"
IMAGE_DEP_ZLIB_NG_VERSION="${IMAGE_DEP_ZLIB_NG_VERSION:-}"
IMAGE_DEP_ZLIB_NG_COMMIT="${IMAGE_DEP_ZLIB_NG_COMMIT:-}"
IMAGE_DEP_OPENSSL_VERSION="${IMAGE_DEP_OPENSSL_VERSION:-}"
IMAGE_DEP_OPENSSL_COMMIT="${IMAGE_DEP_OPENSSL_COMMIT:-}"
IMAGE_DEP_MIMALLOC_VERSION="${IMAGE_DEP_MIMALLOC_VERSION:-}"
IMAGE_DEP_MIMALLOC_COMMIT="${IMAGE_DEP_MIMALLOC_COMMIT:-}"
IMAGE_DEP_NGX_BROTLI_COMMIT="${IMAGE_DEP_NGX_BROTLI_COMMIT:-}"
IMAGE_DEP_NGX_FANCYINDEX_VERSION="${IMAGE_DEP_NGX_FANCYINDEX_VERSION:-}"
IMAGE_DEP_NGX_FANCYINDEX_COMMIT="${IMAGE_DEP_NGX_FANCYINDEX_COMMIT:-}"
IMAGE_FREENGINX_VERSION="${IMAGE_FREENGINX_VERSION:-}"
IMAGE_FREENGINX_COMMIT="${IMAGE_FREENGINX_COMMIT:-}"
IMAGE_BUILD_REVISION="${IMAGE_BUILD_REVISION:-}"

IMAGE_NAME="${IMAGE_NAME:-}"
IMAGE_REGISTRY="${IMAGE_REGISTRY:-}"

while [[ $# -gt 0 ]]; do
	case "$1" in
	--push)
		PUSH=true
		shift
		;;
	*)
		echo "Unknown option: '$1'"
		exit 1
		;;
	esac
done

for var in \
	IMAGE_NAME \
	IMAGE_REGISTRY \
	IMAGE_DEP_PCRE_VERSION \
	IMAGE_DEP_PCRE_COMMIT \
	IMAGE_DEP_ZLIB_NG_VERSION \
	IMAGE_DEP_ZLIB_NG_COMMIT \
	IMAGE_DEP_OPENSSL_VERSION \
	IMAGE_DEP_OPENSSL_COMMIT \
	IMAGE_DEP_MIMALLOC_VERSION \
	IMAGE_DEP_MIMALLOC_COMMIT \
	IMAGE_DEP_NGX_BROTLI_COMMIT \
	IMAGE_DEP_NGX_FANCYINDEX_VERSION \
	IMAGE_DEP_NGX_FANCYINDEX_COMMIT \
	IMAGE_FREENGINX_VERSION \
	IMAGE_FREENGINX_COMMIT \
	IMAGE_BUILD_REVISION; do
	if [ -z "${!var}" ]; then
		echo "Missing required variable: $var"
		exit 1
	fi
done

IMAGE_REPO="${IMAGE_REGISTRY}/${IMAGE_NAME}"

IMAGE_FREENGINX_VERSION_MAJOR=$(echo "${IMAGE_FREENGINX_VERSION%%-*}" | awk -F. '{print $1}')
IMAGE_FREENGINX_VERSION_MINOR=$(echo "${IMAGE_FREENGINX_VERSION%%-*}" | awk -F. '{print $2}')
IMAGE_FREENGINX_VERSION_PATCH=$(echo "${IMAGE_FREENGINX_VERSION%%-*}" | awk -F. '{print $3}')

IMAGE_FREENGINX_VERSION_MAJOR=${IMAGE_FREENGINX_VERSION_MAJOR:-0}
IMAGE_FREENGINX_VERSION_MINOR=${IMAGE_FREENGINX_VERSION_MINOR:-0}
IMAGE_FREENGINX_VERSION_PATCH=${IMAGE_FREENGINX_VERSION_PATCH:-0}

IMAGE_TAG_FULL_QUALIFIED="${IMAGE_REPO}:${IMAGE_FREENGINX_VERSION}-r${IMAGE_BUILD_REVISION}"
IMAGE_TAG_MAJOR_MINOR_PATCH="${IMAGE_REPO}:${IMAGE_FREENGINX_VERSION_MAJOR}.${IMAGE_FREENGINX_VERSION_MINOR}.${IMAGE_FREENGINX_VERSION_PATCH}"
IMAGE_TAG_MAJOR_MINOR="${IMAGE_REPO}:${IMAGE_FREENGINX_VERSION_MAJOR}.${IMAGE_FREENGINX_VERSION_MINOR}"
IMAGE_TAG_MAJOR="${IMAGE_REPO}:${IMAGE_FREENGINX_VERSION_MAJOR}"
IMAGE_TAG_LATEST="${IMAGE_REPO}:latest"

# ================================
# VCS Information

git config --global --add safe.directory "*" 2>/dev/null || true

IMAGE_VCS_DATE_EPOCH=$(git log -1 --pretty=%ct)
IMAGE_VCS_DATE=$(date -u -d @$IMAGE_VCS_DATE_EPOCH +'%Y-%m-%dT%H:%M:%S+00:00')
IMAGE_VCS_REV=$(git rev-parse HEAD)

# ================================
# Build

LOCAL_MANIFEST="localhost/${IMAGE_NAME}:build"

buildah manifest rm "${LOCAL_MANIFEST}" 2>/dev/null || true
buildah manifest create "${LOCAL_MANIFEST}"

arch="amd64"
tag="localhost/${IMAGE_NAME}:build-${arch}"

buildah build \
	--no-cache \
	--jobs=1 \
	--timestamp=${IMAGE_VCS_DATE_EPOCH} \
	--build-arg IMAGE_VCS_DATE=$IMAGE_VCS_DATE \
	--build-arg IMAGE_VCS_REV=$IMAGE_VCS_REV \
	--build-arg IMAGE_DEP_PCRE_VERSION=$IMAGE_DEP_PCRE_VERSION \
	--build-arg IMAGE_DEP_PCRE_COMMIT=$IMAGE_DEP_PCRE_COMMIT \
	--build-arg IMAGE_DEP_ZLIB_NG_VERSION=$IMAGE_DEP_ZLIB_NG_VERSION \
	--build-arg IMAGE_DEP_ZLIB_NG_COMMIT=$IMAGE_DEP_ZLIB_NG_COMMIT \
	--build-arg IMAGE_DEP_OPENSSL_VERSION=$IMAGE_DEP_OPENSSL_VERSION \
	--build-arg IMAGE_DEP_OPENSSL_COMMIT=$IMAGE_DEP_OPENSSL_COMMIT \
	--build-arg IMAGE_DEP_MIMALLOC_VERSION=$IMAGE_DEP_MIMALLOC_VERSION \
	--build-arg IMAGE_DEP_MIMALLOC_COMMIT=$IMAGE_DEP_MIMALLOC_COMMIT \
	--build-arg IMAGE_DEP_NGX_BROTLI_COMMIT=$IMAGE_DEP_NGX_BROTLI_COMMIT \
	--build-arg IMAGE_DEP_NGX_FANCYINDEX_VERSION=$IMAGE_DEP_NGX_FANCYINDEX_VERSION \
	--build-arg IMAGE_DEP_NGX_FANCYINDEX_COMMIT=$IMAGE_DEP_NGX_FANCYINDEX_COMMIT \
	--build-arg IMAGE_FREENGINX_VERSION=$IMAGE_FREENGINX_VERSION \
	--build-arg IMAGE_FREENGINX_COMMIT=$IMAGE_FREENGINX_COMMIT \
	--build-arg IMAGE_BUILD_REVISION=$IMAGE_BUILD_REVISION \
	--format docker \
	-t "$tag" \
	-f Dockerfile .

buildah manifest add --os linux --arch "$arch" "${LOCAL_MANIFEST}" "$tag"

# ================================
# Push

if [ "$PUSH" = true ]; then
	echo "$IMAGE_REGISTRY_PASSWORD" | buildah login "$IMAGE_REGISTRY" -u "$IMAGE_REGISTRY_USERNAME" --password-stdin

	for tag in \
		"${IMAGE_TAG_FULL_QUALIFIED}" \
		"${IMAGE_TAG_MAJOR_MINOR_PATCH}" \
		"${IMAGE_TAG_MAJOR_MINOR}" \
		"${IMAGE_TAG_MAJOR}" \
		"${IMAGE_TAG_LATEST}"; do
		echo "Pushing images, tagging: ${tag}..."
		buildah manifest push --all "${LOCAL_MANIFEST}" "docker://${tag}"
	done
else
	echo "Skipping images push..."
fi
